### ISSUE TITLE
Удаление треков, вопрос

### ISSUE THREAD

**Issue by macik** [1999/listen#100]
Удалил пачку треков, нажав «крестик» —  они серенькими стали. Но их воспроизведение все равно идет, что при проигрываниии всего листа подряд, что когда включаешь рандом. 
Что мне показалось не логично. Это так и задумано?

Только после повторного захода на «home» треки исчезли из списка.

**Comment by 1999** [comment]
Да, так и задумано. Это сделано, чтобы можно было передумать и восстановить трек.
