### ISSUE TITLE
Фото артистов плющит

### ISSUE THREAD

**Issue by makoni** [1999/listen#106]
Можно, чтобы их не плющило и сохранялись пропорции? https://yadi.sk/i/YFJO7A3ye2ZhV

**Comment by 1999** [comment]
Можно. Я могу сам поправить на выходных или ты можешь успеть сделать пулреквест. Что выберешь?

**Comment by makoni** [comment]
я выбрал выходные :)

**Comment by 1999** [comment]
Обидно. По высоте все фотки разные. А по ширине зафиксированы

**Comment by makoni** [comment]
Ну так обрезай просто их до квадрата и всё :)

**Comment by 1999** [comment]
Ты не понял. Там размеры 100x90, 100x80. До чего это обрезать?

**Comment by makoni** [comment]
Сделать 100x100 блок, а картинку просто бэкграундом по центра с чёрными полями. всяко приятнее будет выглядеть

**Comment by 1999** [comment]
Логично. Пулреквесть :+1:
