### ISSUE TITLE
Может поменять иконку настроек?

### ISSUE THREAD

**Issue by makoni** [1999/listen#107]
Сэндвич, как бы, обычно меню какое-то открывает или панельку всплывающие. А для настроек принятно шестеренки или гаечные ключи?

![screen shot 2015-01-16 at 13 51 35](https://cloud.githubusercontent.com/assets/234015/5775113/e57a5234-9d86-11e4-9b2d-e7d51f54b02e.png)

**Comment by 1999** [comment]
Эх. Раньше сэндвич открывал настройки в Хроме и я надеялся. А теперь черт его знает
