### ISSUE TITLE
Проблемные правый и левый слеши (\ /)

### ISSUE THREAD

**Issue by VitalikOrlioglo** [1999/listen#111]
Если запись в названии имеет правый или левый слеш (\ /), то запись не загружается, так же проверил со знаком "|", с этим знаком всё норм.
Проверил только вот эти три знака на пару десятков аудиозаписей
Windows7: версия Google Chrome 48.0.2564.116 m
Elementary OS Luna 0.2.1: Google Chrome version 48.0.2564.116

**Comment by 1999** [comment]
Главная проблема была тут:
```
-                var percents = Math.floor((evt.position / evt.totalSize) * 100);
+                var percents = Math.floor((evt.loaded / evt.total) * 100);
```

В Chrome поменяли API для `progress` события в XHR
